# This file was generated by GoReleaser. DO NOT EDIT.
class Todocli < Formula
  desc "ToDoCli is a simple cli saving your time by managing your tasks from your terminal."
  homepage ""
  version "1.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wstnbrg/todocli/releases/download/1.0.4/todocli_1.0.4_Darwin_x86_64.tar.gz"
    sha256 "c90c00ab2813fd9fc4279133e10e2b07ed197885cc2ce4f58d76e7c5f748c627"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wstnbrg/todocli/releases/download/1.0.4/todocli_1.0.4_Linux_x86_64.tar.gz"
      sha256 "3a70fbf16b912cee205b338aff2e3b6c80e5ce09181a18f16e47ab95318475b2"
    end
  end

  def install
    bin.install "todocli"
  end
end
