# This file was generated by GoReleaser. DO NOT EDIT.
class Todocli < Formula
  desc "ToDoCli is a simple cli saving your time by managing your tasks from your terminal."
  homepage "https://github.com/wstnbrg/todocli"
  version "1.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wstnbrg/todocli/releases/download/1.0.6/todocli_1.0.6_Darwin_x86_64.tar.gz"
    sha256 "78313a0e6717236339cff3b6f69d0f6e11b1dc87dddb453733ae7eab36026c5a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wstnbrg/todocli/releases/download/1.0.6/todocli_1.0.6_Linux_x86_64.tar.gz"
      sha256 "e19e326a12a7d08361454c8120fab2a7f72faac70aa91c596d0213aa47ef6c09"
    end
  end

  def install
    bin.install "todocli"
  end
end
