# This file was generated by GoReleaser. DO NOT EDIT.
class Todocli < Formula
  desc "ToDoCli is a simple cli saving your time by managing your tasks from your terminal."
  homepage "https://github.com/wstnbrg/todocli"
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wstnbrg/todocli/releases/download/1.1.1/todocli_1.1.1_Darwin_x86_64.tar.gz"
    sha256 "cdd47dbfd07a56a50972f8520fe73a3f4aeb976db87175df40294fbbb0639824"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wstnbrg/todocli/releases/download/1.1.1/todocli_1.1.1_Linux_x86_64.tar.gz"
      sha256 "d80f5c5536a19b66fb802fd4cd2a7b02584e0071531ad69f716a82b803a56c5c"
    end
  end

  def install
    bin.install "todocli"
  end
end
